### ISSUE TITLE
Custom build fails if @text is not included

### ISSUE THREAD

**Issue by sdcooke** [google/shaka-player#1115]
When creating a custom build with the `v2.2.5` tag the following happens:

```bash
$ python build.py +@dash +@networking +@polyfill
[INFO] Compiling the library...
/Users/sam/Development/open-source/shaka-player/lib/player.js:1996: ERROR - missing require: 'shaka.text.SimpleTextDisplayer'
      return new shaka.text.SimpleTextDisplayer(videoElement);
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The following works:

```bash
python build.py +@dash +@networking +@polyfill +@text
```

I would have expected `@text` to be optional.

I started modifying some files to see if it was a quick fix but just hit more code that relied on `shaka.text`.

**Comment by joeyparrish** [comment]
Definitely seems like a bug.  Any core (required) components related to text should be in the "core" list of sources, not "text".

**Comment by joeyparrish** [comment]
Fix cherry-picked to v2.2.6.
